server {
    listen 8082;
    server_name tabulation-filament.local *.tabulation-filament.local 192.168.1.2;

    root C:/laragon/www/tabulation/tabulation-filament/public;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass php_upstream;
        fastcgi_index index.php;

        include fastcgi.conf;
    }
	
	location = /test {
    return 200 "THIS SERVER BLOCK IS ACTIVE";
	}
}